@startuml

!theme toy

box SensorVision App #grey
    participant SensorVisionClient as Client
    participant MetadataState as State
    participant MqttClientWrapper as Mqtt
end box

participant "Mosquitto Broker" as Broker
participant "IoT Agent" as Agent

== Delete Sensor ==
--> Client ++: delete_sensor\n[sensor_id]
note right Client: According to [[https://docs-iot.teamviewer.com/mqtt-api/#534-delete Sensor/Delete]]
Client -> Mqtt --++: async_message to /sensor/<sensor_id>/delete "{}"
Mqtt -> Broker --++: <forward> via request_client
Broker -> Agent --++: <forward>
Agent -> Agent : Delete Sensor
Broker <-- Agent --++: "Sensor was deleted."
Mqtt <-- Broker --++: <forward>
State <-- Mqtt --++: Call mqtt_callback\n[topic] [message]
State -> State ++: Call SensorDelete\ncallback
note over State
Drop subscriptions to the
following sensor-aware response
topics using Sensor ID:
* [[https://docs-iot.teamviewer.com/mqtt-api/#533-update Sensor/Update]]
* [[https://docs-iot.teamviewer.com/mqtt-api/#534-delete Sensor/Delete]]

* [[https://docs-iot.teamviewer.com/mqtt-api/#541-create Metric/Create]]
* [[https://docs-iot.teamviewer.com/mqtt-api/#543-update Metric/Update]]
* [[https://docs-iot.teamviewer.com/mqtt-api/#534-delete Metric/Delete]]

* [[https://docs-iot.teamviewer.com/mqtt-api/#51-push-metric-values Sensor/PushValues]]
* [[https://docs-iot.teamviewer.com/mqtt-api/#52-get-metric-values Sensor/Livedata]]
end note
State -> State ++--: Unsubscribe from sensor events
loop for each Metric ID in Sensor
note over State
Drop subscriptions to the
following metric-aware response
topics using Sensor ID and Metric ID:
* [[https://docs-iot.teamviewer.com/mqtt-api/#542-describe Metric/Describe]]
end note
State -> State ++--: Unsubscribe from metric events
end
State -> State : Delete Sensor Entry
Client <-- State --++: Fire SensorDeleted Event\n[sensor_id]
deactivate State

<-- Client --: Fire SensorDeleted Event

@enduml
