@startuml

!theme toy

box SensorVision App #grey
    participant SensorVisionClient as Client
    participant MetadataState as State
    participant MqttClient as mqtt
end box

participant "Mosquitto Broker" as Broker
participant "IoT Agent" as Agent

== Generate clientCert.crt ==
mqtt -> mqtt ++--: Read ./csr.pem and its hash
mqtt --> Broker : Subscribe to /certBack/{hash}
mqtt -> Broker ++: Post csr.pem to /v1.0/


@enduml
